### PR TITLE
streamlit-pandas-profiling 0.1.3 :snowflake:

### PR DESCRIPTION
**Pull request by lorepirri**
streamlit-pandas-profiling 0.1.3 :snowflake:

**Destination channel:** Snowflake

### Links

- [PKG-3729]
- dev_url (pypi): https://github.com/okld/streamlit-pandas-profiling/tree/0.1.3
- conda-forge: https://github.com/conda-forge/streamlit-pandas-profiling-feedstock/blob/main/recipe/meta.yaml
- pypi: https://pypi.org/project/streamlit-pandas-profiling

### Explanation of changes:

- fix recipe
- add patch to fix the version number, for some reason `setuptools` is not able to get the version with the error:
    ```
        AttributeError: module 'streamlit_pandas_profiling' has no attribute '__version__'
    ```

[PKG-3729]: https://anaconda.atlassian.net/browse/PKG-3729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]

**Comment by M-Waszkiewicz-Anaconda** [comment]
have you run conda debug with the __version__ issue, this looks weird

**Comment by lorepirri** [comment]
> have you run conda debug with the **version** issue, this looks weird

no @M-Waszkiewicz-Anaconda but reading posts like https://stackoverflow.com/questions/72167802/adding-version-attribute-to-python-module it seems that `setuptools` changed the way handles the dynamic version in recent versions

**Comment by M-Waszkiewicz-Anaconda** [comment]
> > have you run conda debug with the **version** issue, this looks weird
> 
> no @M-Waszkiewicz-Anaconda but reading posts like https://stackoverflow.com/questions/72167802/adding-version-attribute-to-python-module it seems that `setuptools` changed the way handles the dynamic version in recent versions

can we try to add setuptools version constraints to make it work instead having a patch ? setuptools >= 61, it is mentioned in the one of the that stackoverflow answers

**Comment by lorepirri** [comment]
using `setuptools: 68.2.2`

```
                   INFO     AttributeError: module 'streamlit_pandas_profiling' has no attribute '__version__'                              

```

https://cloud.prefect.io/anaconda/flow-run/ffef79a0-4d47-4f75-b388-4d43202c7514

**Comment by M-Waszkiewicz-Anaconda** [comment]
> using `setuptools: 68.2.2`
> 
> ```
>                    INFO     AttributeError: module 'streamlit_pandas_profiling' has no attribute '__version__'                              
> ```
> 
> https://cloud.prefect.io/anaconda/flow-run/ffef79a0-4d47-4f75-b388-4d43202c7514

if still does not work, then we need to keep the patch, thank you for trying it out

**Comment by JeanChristopheMorinPerso** [comment]
You can simplify the patch a little bit by changing https://github.com/okld/streamlit-pandas-profiling/blob/main/setup.cfg#L3 to `version = attr: streamlit_pandas_profiling.version.__version__`. Patching will be required because of small differences in implementations details inside setuptools.

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Pull request merged**
